-- 1. Table pelanggans
CREATE TABLE public.pelanggans (
    id bigint generated by default as identity primary key,
    nama_pelanggan varchar(100) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    tgl_lahir date,
    telepon varchar(15),
    alamat1 varchar(255),
    alamat2 varchar(255),
    alamat3 varchar(255),
    kartu_id varchar(255),
    foto varchar(255),
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Table users (admin, owner, kurir)
CREATE TABLE public.users (
    id bigint generated by default as identity primary key,
    name varchar(30) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    level text check (level in ('admin', 'owner', 'kurir')),
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Table jenis_pembayarans
CREATE TABLE public.jenis_pembayarans (
    id bigint generated by default as identity primary key,
    metode_pembayaran varchar(30) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Table detail_jenis_pembayarans
CREATE TABLE public.detail_jenis_pembayarans (
    id bigint generated by default as identity primary key,
    id_jenis_pembayaran bigint references public.jenis_pembayarans(id) on delete cascade,
    no_rek varchar(25),
    tempat_bayar varchar(50),
    logo varchar(255),
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Table pakets
CREATE TABLE public.pakets (
    id bigint generated by default as identity primary key,
    nama_paket varchar(50) not null,
    jenis text check (jenis in ('Prasmanan', 'Box')),
    kategori text check (kategori in ('Pernikahan', 'Selamatan', 'Ulang Tahun', 'Studi Tour', 'Rapat')),
    jumlah_pax integer,
    harga_paket integer,
    deskripsi text,
    foto1 varchar(255),
    foto2 varchar(255),
    foto3 varchar(255),
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Table pesanans
CREATE TABLE public.pesanans (
    id bigint generated by default as identity primary key,
    id_pelanggan bigint references public.pelanggans(id) on delete cascade,
    id_jenis_bayar bigint references public.jenis_pembayarans(id) on delete set null,
    no_resi varchar(30),
    tgl_pesan timestamp with time zone,
    status_pesan text check (status_pesan in ('Menunggu Konfirmasi', 'Sedang Diproses', 'Menunggu Kurir')),
    total_bayar bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Table detail_pemesanans (Pivot table with composite PK)
CREATE TABLE public.detail_pemesanans (
    id_pemesanan bigint references public.pesanans(id) on delete cascade,
    id_paket bigint references public.pakets(id) on delete cascade,
    subtotal bigint,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now()),
    primary key (id_pemesanan, id_paket)
);

-- 8. Table pengirimans
CREATE TABLE public.pengirimans (
    id bigint generated by default as identity primary key,
    tgl_kirim timestamp with time zone,
    tgl_tiba timestamp with time zone,
    status_kirim text check (status_kirim in ('Sedang Dikirim', 'Tiba Ditujuan')),
    bukti_foto varchar(255),
    id_pesan bigint references public.pesanans(id) on delete cascade,
    id_user bigint references public.users(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 9. Insert Default Data for Testing
INSERT INTO public.users (name, email, password, level) VALUES ('Admin Utama', 'admin@gmail.com', 'admin123', 'admin');
INSERT INTO public.jenis_pembayarans (metode_pembayaran) VALUES ('Transfer BCA'), ('Mandiri'), ('Cash di Tempat');
